### ISSUE TITLE
Fake Samsung Pay app stays oppen in the background.

### ISSUE THREAD

**Issue by 4k3or3et** [blunden/SPayToGPay#3]
Hi

The app works great. Best I have tried from all this kind.

I would like to suggest an improvement. Now when you hold the button, it opens Google Wallet but fake Samsung Pay app stays open in the background:

![Screenshot_20230331_091054_recent](https://user-images.githubusercontent.com/53837030/229050018-0d1191de-3651-4bf2-a344-f4630e02dae6.png)

Is there any chance to implement function which automatically will close the fake Samsung Pay app after opening Google wallet?

**Comment by blunden** [comment]
It shouldn't actually be running in the background if you check the code, it just shows up in the recent app menu (which is what that menu is).

There is a manifest entry that can be used to hide apps from recents that I could try (presumably it works on the watch as well), but I would need help testing the app since I'm unable to use it myself.

**Comment by 4k3or3et** [comment]
If you would be able to provide the APK I am happy to test.

**Comment by blunden** [comment]
@4k3or3et Give this APK a try:

https://www.mediafire.com/file/6mekqz8620fn6y0/SPayToGPay-test.apk/file

**Comment by 4k3or3et** [comment]
Thanks!

Can I just install it or should I uninstall the old version first?

**Comment by blunden** [comment]
Just install it on top of the other one.

**Comment by 4k3or3et** [comment]
Coolest thing ever!

Works as expected and it does not show the fake Samsung Pay app in the recent apps list.

For me it could be promoted to version 1.2.

Thanks a million for your efforts :-)

**Comment by blunden** [comment]
Great, thanks!
